export type Theme = 'light' | 'dark' | 'ocean' | 'forest' | 'sunset' | 'midnight' | 'nordic' | 'warm' | 'jonas' | 'cyberpunk' | 'retro' | 'nature' | 'monochrome' | 'gangsta' | 'fika';

export interface ThemeVocabulary {
  appTitle: string;
  footerText: string;
  navFileOverview: string;
  navTasks: string;
  navRecords: string;
  navTINSearch: string;
  navUtils: string;
  themeSection: string;
  themeDescription: string;
  databaseSection: string;
  dangerZone: string;
  purgeButton: string;
  cancelButton: string;
  confirmButton: string;
  uploadButton: string;
  refreshButton: string;
  filterAll: string;
  filterAccepted: string;
  filterRejected: string;
  filterValidating: string;
  statusAccepted: string;
  statusRejected: string;
  statusValidating: string;
  errorsLabel: string;
  warningsLabel: string;
  processingLabel: string;
  noDataMessage: string;
}

export const vocabularies: Record<Theme, ThemeVocabulary> = {
  light: {
    appTitle: 'AEOI Exchange Service',
    footerText: 'AEOI Exchange Service (DAC2/CRS) - MVP Demo',
    navFileOverview: 'File Overview',
    navTasks: 'Tasks',
    navRecords: 'Records',
    navTINSearch: 'TIN Search',
    navUtils: 'Utils',
    themeSection: 'Visual Theme',
    themeDescription: 'Choose a theme that suits your style. Your selection will be saved automatically.',
    databaseSection: 'Database Management',
    dangerZone: 'Danger Zone',
    purgeButton: 'Purge Database',
    cancelButton: 'Cancel',
    confirmButton: 'Yes, Purge Everything',
    uploadButton: 'Upload File',
    refreshButton: 'Refresh',
    filterAll: 'All',
    filterAccepted: 'Accepted',
    filterRejected: 'Rejected',
    filterValidating: 'Validating',
    statusAccepted: 'Accepted',
    statusRejected: 'Rejected',
    statusValidating: 'Validating',
    errorsLabel: 'Errors',
    warningsLabel: 'Warnings',
    processingLabel: 'Processing',
    noDataMessage: 'No files found'
  },
  dark: {
    appTitle: 'AEOI Exchange Service',
    footerText: 'AEOI Exchange Service (DAC2/CRS) - MVP Demo',
    navFileOverview: 'File Overview',
    navTasks: 'Tasks',
    navRecords: 'Records',
    navTINSearch: 'TIN Search',
    navUtils: 'Settings',
    themeSection: 'Appearance Settings',
    themeDescription: 'Select your preferred visual aesthetic. Changes persist across sessions.',
    databaseSection: 'Data Control',
    dangerZone: 'Critical Operations',
    purgeButton: 'Obliterate Database',
    cancelButton: 'Abort',
    confirmButton: 'Confirm Deletion',
    uploadButton: 'Upload',
    refreshButton: 'Refresh',
    filterAll: 'All',
    filterAccepted: 'Accepted',
    filterRejected: 'Rejected',
    filterValidating: 'Processing',
    statusAccepted: 'Accepted',
    statusRejected: 'Rejected',
    statusValidating: 'Processing',
    errorsLabel: 'Errors',
    warningsLabel: 'Warnings',
    processingLabel: 'Processing',
    noDataMessage: 'No files available'
  },
  ocean: {
    appTitle: 'AEOI WAVE EXCHANGE',
    footerText: 'AEOI Wave Exchange (DAC2/CRS) - Anchored Demo',
    navFileOverview: 'CARGO MANIFEST',
    navTasks: 'SHIP ORDERS',
    navRecords: 'LOGBOOK',
    navTINSearch: 'BEACON SEARCH',
    navUtils: 'CONTROLS',
    themeSection: 'WAVE STYLE',
    themeDescription: 'Dive into your preferred aesthetic. Anchored automatically to your profile.',
    databaseSection: 'FLEET MANAGEMENT',
    dangerZone: 'Deep Waters',
    purgeButton: 'Sink Database',
    cancelButton: 'Resurface',
    confirmButton: 'Scuttle All Data',
    uploadButton: 'Load Cargo',
    refreshButton: 'Check Tides',
    filterAll: 'All Ships',
    filterAccepted: 'Docked',
    filterRejected: 'Sunk',
    filterValidating: 'Sailing',
    statusAccepted: 'Docked',
    statusRejected: 'Sunk',
    statusValidating: 'Sailing',
    errorsLabel: 'Leaks',
    warningsLabel: 'Warnings',
    processingLabel: 'Navigating',
    noDataMessage: 'Empty harbor'
  },
  forest: {
    appTitle: 'AEOI Exchange Service',
    footerText: 'AEOI Exchange Service (DAC2/CRS) - MVP Demo',
    navFileOverview: 'Files',
    navTasks: 'Tasks',
    navRecords: 'Records',
    navTINSearch: 'Search',
    navUtils: 'Config',
    themeSection: 'Theme Configuration',
    themeDescription: 'Select theme. Preference stored locally.',
    databaseSection: 'Database Operations',
    dangerZone: 'High Risk Area',
    purgeButton: 'Clear Database',
    cancelButton: 'Cancel',
    confirmButton: 'Execute Purge',
    uploadButton: 'Upload',
    refreshButton: 'Reload',
    filterAll: 'All',
    filterAccepted: 'Accepted',
    filterRejected: 'Rejected',
    filterValidating: 'Validating',
    statusAccepted: 'Accepted',
    statusRejected: 'Rejected',
    statusValidating: 'Validating',
    errorsLabel: 'Errors',
    warningsLabel: 'Warnings',
    processingLabel: 'Processing',
    noDataMessage: 'No files'
  },
  sunset: {
    appTitle: 'AEOI Glow Exchange',
    footerText: 'AEOI Glow Exchange (DAC2/CRS) - Radiant Demo',
    navFileOverview: 'File Vibes',
    navTasks: 'Task Glow',
    navRecords: 'Record Horizon',
    navTINSearch: 'TIN Radiance',
    navUtils: 'Style Studio',
    themeSection: 'Color Vibes',
    themeDescription: 'Pick your perfect palette and let it glow across your experience.',
    databaseSection: 'Data Horizon',
    dangerZone: 'Burnout Zone',
    purgeButton: 'Incinerate Database',
    cancelButton: 'Cool Down',
    confirmButton: 'Blaze It All',
    uploadButton: 'Ignite Upload',
    refreshButton: 'Rekindle',
    filterAll: 'All Flames',
    filterAccepted: 'Glowing',
    filterRejected: 'Extinguished',
    filterValidating: 'Sparking',
    statusAccepted: 'Glowing',
    statusRejected: 'Extinguished',
    statusValidating: 'Sparking',
    errorsLabel: 'Burns',
    warningsLabel: 'Sparks',
    processingLabel: 'Blazing',
    noDataMessage: 'No embers'
  },
  midnight: {
    appTitle: 'AEOI Void Exchange',
    footerText: 'AEOI Void Exchange (DAC2/CRS) - Dimensional Demo',
    navFileOverview: 'File Void',
    navTasks: 'Task Realm',
    navRecords: 'Record Dimension',
    navTINSearch: 'TIN Portal',
    navUtils: 'Reality Control',
    themeSection: 'Interface Mode',
    themeDescription: 'Choose your dimension. Your reality persists eternally.',
    databaseSection: 'Data Void',
    dangerZone: 'Event Horizon',
    purgeButton: 'Erase Existence',
    cancelButton: 'Return',
    confirmButton: 'Delete Reality',
    uploadButton: 'Materialize',
    refreshButton: 'Rewind Time',
    filterAll: 'All Entities',
    filterAccepted: 'Manifested',
    filterRejected: 'Erased',
    filterValidating: 'Phasing',
    statusAccepted: 'Manifested',
    statusRejected: 'Erased',
    statusValidating: 'Phasing',
    errorsLabel: 'Anomalies',
    warningsLabel: 'Distortions',
    processingLabel: 'Transcending',
    noDataMessage: 'Void empty'
  },
  nordic: {
    appTitle: 'AEOI Exchange',
    footerText: 'AEOI Exchange (DAC2/CRS) - Demo',
    navFileOverview: 'Files',
    navTasks: 'Tasks',
    navRecords: 'Records',
    navTINSearch: 'Search',
    navUtils: 'Settings',
    themeSection: 'Theme',
    themeDescription: 'Select theme. Saved automatically.',
    databaseSection: 'Database',
    dangerZone: 'Warning',
    purgeButton: 'Purge',
    cancelButton: 'Cancel',
    confirmButton: 'Confirm',
    uploadButton: 'Upload',
    refreshButton: 'Refresh',
    filterAll: 'All',
    filterAccepted: 'Accepted',
    filterRejected: 'Rejected',
    filterValidating: 'Validating',
    statusAccepted: 'Accepted',
    statusRejected: 'Rejected',
    statusValidating: 'Validating',
    errorsLabel: 'Errors',
    warningsLabel: 'Warnings',
    processingLabel: 'Processing',
    noDataMessage: 'No files'
  },
  warm: {
    appTitle: 'AEOI Cozy Exchange',
    footerText: 'AEOI Cozy Exchange (DAC2/CRS) - Homey Demo',
    navFileOverview: 'File Cabinet',
    navTasks: 'To-Dos',
    navRecords: 'Recipe Box',
    navTINSearch: 'Find Things',
    navUtils: 'Home Settings',
    themeSection: 'Cozy Settings',
    themeDescription: 'Find your comfort zone. We\'ll remember your favorite spot.',
    databaseSection: 'Kitchen Cleanup',
    dangerZone: 'Hot Stove',
    purgeButton: 'Empty Everything',
    cancelButton: 'Keep It',
    confirmButton: 'Clear the Table',
    uploadButton: 'Add to Shelf',
    refreshButton: 'Check Again',
    filterAll: 'Whole Cabinet',
    filterAccepted: 'Ready to Serve',
    filterRejected: 'Spoiled',
    filterValidating: 'Cooking',
    statusAccepted: 'Ready',
    statusRejected: 'Spoiled',
    statusValidating: 'Cooking',
    errorsLabel: 'Burnt',
    warningsLabel: 'Careful',
    processingLabel: 'Preparing',
    noDataMessage: 'Cabinet empty'
  },
  jonas: {
    appTitle: 'AEOI Exchange Platform',
    footerText: 'AEOI Exchange Platform (DAC2/CRS) - Experience Demo',
    navFileOverview: 'Document Center',
    navTasks: 'Workflow',
    navRecords: 'Registry',
    navTINSearch: 'Identifier Search',
    navUtils: 'Preferences',
    themeSection: 'Experience Mode',
    themeDescription: 'Curate your digital environment. Preferences sync seamlessly.',
    databaseSection: 'System Control',
    dangerZone: 'Protected Zone',
    purgeButton: 'Reset System',
    cancelButton: 'Dismiss',
    confirmButton: 'Authorize Reset',
    uploadButton: 'Import Document',
    refreshButton: 'Synchronize',
    filterAll: 'All Documents',
    filterAccepted: 'Verified',
    filterRejected: 'Declined',
    filterValidating: 'Processing',
    statusAccepted: 'Verified',
    statusRejected: 'Declined',
    statusValidating: 'Processing',
    errorsLabel: 'Issues',
    warningsLabel: 'Notices',
    processingLabel: 'Analyzing',
    noDataMessage: 'No documents available'
  },
  cyberpunk: {
    appTitle: '>> AEOI_MAINFRAME',
    footerText: '>> AEOI_MAINFRAME (DAC2/CRS) - SYSTEM_DEMO',
    navFileOverview: '>> DATA_CACHE',
    navTasks: '>> TASK_QUEUE',
    navRecords: '>> RECORD_ARRAY',
    navTINSearch: '>> ID_LOOKUP',
    navUtils: '>> SYS_CONFIG',
    themeSection: '>> VISUAL_PROTOCOL',
    themeDescription: 'Jack into your preferred interface. Neural cache updated real-time.',
    databaseSection: '>> DATA_MAINFRAME',
    dangerZone: 'ICE BARRIER',
    purgeButton: 'Nuke Database',
    cancelButton: 'Jack Out',
    confirmButton: 'Execute Wipe',
    uploadButton: 'Upload Payload',
    refreshButton: 'Resync Matrix',
    filterAll: 'All Nodes',
    filterAccepted: 'Authorized',
    filterRejected: 'Firewall Block',
    filterValidating: 'Decrypting',
    statusAccepted: 'Authorized',
    statusRejected: 'Blocked',
    statusValidating: 'Decrypting',
    errorsLabel: 'Critical',
    warningsLabel: 'Alert',
    processingLabel: 'Computing',
    noDataMessage: 'Cache empty'
  },
  retro: {
    appTitle: '★ AEOI ARCADE ★',
    footerText: '★ AEOI ARCADE (DAC2/CRS) - Totally Rad Demo ★',
    navFileOverview: '★ File Zone',
    navTasks: '★ Quest Log',
    navRecords: '★ High Scores',
    navTINSearch: '★ ID Finder',
    navUtils: '★ Power-Ups',
    themeSection: '★ Style Select ★',
    themeDescription: 'Choose your rad look! Totally saves your pick automatically.',
    databaseSection: '★ Data Arcade ★',
    dangerZone: 'Game Over Zone',
    purgeButton: 'Delete High Scores',
    cancelButton: 'Back',
    confirmButton: 'Reset Console',
    uploadButton: 'Insert Disk',
    refreshButton: 'Replay',
    filterAll: 'All Levels',
    filterAccepted: 'Victory!',
    filterRejected: 'Game Over',
    filterValidating: 'Playing',
    statusAccepted: 'Victory',
    statusRejected: 'Game Over',
    statusValidating: 'Playing',
    errorsLabel: 'Bugs',
    warningsLabel: 'Glitches',
    processingLabel: 'Loading',
    noDataMessage: 'No saves found'
  },
  nature: {
    appTitle: 'AEOI Garden Exchange',
    footerText: 'AEOI Garden Exchange (DAC2/CRS) - Organic Demo',
    navFileOverview: 'Seed Collection',
    navTasks: 'Growth Tasks',
    navRecords: 'Plant Log',
    navTINSearch: 'Root Search',
    navUtils: 'Garden Tools',
    themeSection: 'Visual Ecosystem',
    themeDescription: 'Cultivate your environment. Your preference takes root naturally.',
    databaseSection: 'Garden Management',
    dangerZone: 'Wildfire Zone',
    purgeButton: 'Clear the Garden',
    cancelButton: 'Preserve',
    confirmButton: 'Uproot Everything',
    uploadButton: 'Plant Seeds',
    refreshButton: 'Water',
    filterAll: 'Whole Garden',
    filterAccepted: 'Blooming',
    filterRejected: 'Wilted',
    filterValidating: 'Growing',
    statusAccepted: 'Blooming',
    statusRejected: 'Wilted',
    statusValidating: 'Growing',
    errorsLabel: 'Blight',
    warningsLabel: 'Pests',
    processingLabel: 'Cultivating',
    noDataMessage: 'Garden empty'
  },
  monochrome: {
    appTitle: 'AEOI_EXCHANGE',
    footerText: 'AEOI_EXCHANGE (DAC2/CRS) - DEMO',
    navFileOverview: 'FILES',
    navTasks: 'TASKS',
    navRecords: 'RECORDS',
    navTINSearch: 'SEARCH',
    navUtils: 'SETTINGS',
    themeSection: 'THEME',
    themeDescription: 'SELECT. SAVE. DONE.',
    databaseSection: 'DATABASE',
    dangerZone: 'CRITICAL',
    purgeButton: 'DELETE',
    cancelButton: 'NO',
    confirmButton: 'YES DELETE ALL',
    uploadButton: 'UPLOAD',
    refreshButton: 'RELOAD',
    filterAll: 'ALL',
    filterAccepted: 'ACCEPTED',
    filterRejected: 'REJECTED',
    filterValidating: 'VALIDATING',
    statusAccepted: 'ACCEPTED',
    statusRejected: 'REJECTED',
    statusValidating: 'VALIDATING',
    errorsLabel: 'ERRORS',
    warningsLabel: 'WARNINGS',
    processingLabel: 'PROCESSING',
    noDataMessage: 'NO FILES'
  },
  gangsta: {
    appTitle: 'AEOI Street Exchange',
    footerText: 'AEOI Street Exchange (DAC2/CRS) - Keepin\' It Real Demo',
    navFileOverview: 'Da Files',
    navTasks: 'Street Biz',
    navRecords: 'The Books',
    navTINSearch: 'Find Homies',
    navUtils: 'Hood Settings',
    themeSection: 'Style Mode',
    themeDescription: 'Pick your fresh look, homie. We keep it locked in for ya.',
    databaseSection: 'Data Vault',
    dangerZone: 'Hot Zone',
    purgeButton: 'Wipe Everything',
    cancelButton: 'Nah Bruh',
    confirmButton: 'Yeah, Smoke It All',
    uploadButton: 'Drop Files',
    refreshButton: 'Check It',
    filterAll: 'Whole Stash',
    filterAccepted: 'Legit',
    filterRejected: 'Busted',
    filterValidating: 'Checkin\'',
    statusAccepted: 'Legit',
    statusRejected: 'Busted',
    statusValidating: 'Checkin\'',
    errorsLabel: 'Problems',
    warningsLabel: 'Watch Out',
    processingLabel: 'Workin\' On It',
    noDataMessage: 'Stash empty, yo'
  },
  fika: {
    appTitle: 'AEOI Fika Exchange',
    footerText: 'AEOI Fika Exchange (DAC2/CRS) - Mysig Demo',
    navFileOverview: 'Fil Översikt',
    navTasks: 'Uppgifter',
    navRecords: 'Register',
    navTINSearch: 'TIN Sökning',
    navUtils: 'Inställningar',
    themeSection: 'Tema Inställningar',
    themeDescription: 'Välj ett tema som passar dig. Ditt val sparas automatiskt, som en varm bulle.',
    databaseSection: 'Databas Hantering',
    dangerZone: 'Varningsområde',
    purgeButton: 'Rensa Databasen',
    cancelButton: 'Avbryt',
    confirmButton: 'Ja, Rensa Allt',
    uploadButton: 'Ladda Upp Fil',
    refreshButton: 'Uppdatera',
    filterAll: 'Alla',
    filterAccepted: 'Godkända',
    filterRejected: 'Avvisade',
    filterValidating: 'Validerar',
    statusAccepted: 'Godkänd',
    statusRejected: 'Avvisad',
    statusValidating: 'Validerar',
    errorsLabel: 'Fel',
    warningsLabel: 'Varningar',
    processingLabel: 'Bearbetar',
    noDataMessage: 'Inga filer hittades'
  }
};

export function getVocabulary(theme: Theme): ThemeVocabulary {
  return vocabularies[theme] || vocabularies.light;
}
